project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
  resources:
    - "*.html"
    - "images/"
    - "CNAME"
    - "robots.txt"
    - "_static"
    - "forms/"
    - "js/"
    - "css/"
  preview:
    port: 4096
website:
  title: "Kudoo"
  description: "Streamline ISO 27001 implementation with Kudoo's Microsoft-integrated GRC platform designed for Australian businesses."
  site-url: https://kudoo.io
  google-analytics: "G-31NNPGK99Z"  
  favicon: "images/logo.png"
  
  open-graph:
    site-name: "Kudoo"
    title: "Kudoo | ISO 27001 Compliance for Australian Organisations"
    description: "Streamline ISO 27001 implementation with Kudoo's Microsoft-integrated GRC platform designed for Australian businesses."
    image: "images/kudoo-social-preview.jpg"
  
  twitter-card:
    creator: "@Kudoo"
    title: "Kudoo | ISO 27001 Compliance for Australian Organisations"
    description: "Streamline ISO 27001 implementation with Kudoo's Microsoft-integrated GRC platform designed for Australian businesses."
    image: "images/kudoo-social-preview.jpg"
  
  navbar:
    background: primary
    foreground: light
    logo: "images/logo.png"
    left:
      - href: index.qmd
        text: Home
      - href: ./content/product.qmd
        text: Product
      - href: ./content/pricing.qmd
        text: Pricing
      - href: ./blog/index.qmd
        text: Blog

  page-footer:
    background: primary
    foreground: light
    left: "© 2025 Kudoo. All rights reserved."
    center: 
      - text: "Privacy Policy"
        href: content/privacy.qmd
      - text: "Terms of Service"
        href: content/terms.qmd
      - text: "Cookie Policy"
        href: content/cookie-policy.qmd
      - text: "Sitemap"
        href: sitemap.xml
    right:
      - icon: linkedin
        href: https://linkedin.com/company/kudoo-cloud
      - icon: twitter-x
        href: https://x.com/KudooCloud
      - icon: facebook
        href: https://www.facebook.com/kudoocloud

  search:
    location: navbar
    type: overlay

format:
  html:
    theme: 
      - flatly
      - custom.scss
    include-in-header:
      - file: includes/schema.html
      - file: includes/meta-tags.html
      - file: includes/cookie-banner.html
      - file: includes/copilot.html
    mainfont: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu"
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: true
    citations-hover: true
    footnotes-hover: true
    toc: false